// <auto-generated />
namespace TeamJAMiN.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201604042258035_userdata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
