// <auto-generated />
namespace TeamJAMiN.DataContexts.GalleristComponentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GameUpdates1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameUpdates1));
        
        string IMigrationMetadata.Id
        {
            get { return "201603030257127_GameUpdates1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
