// <auto-generated />
namespace TeamJAMiN.DataContexts.GalleristComponentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class executiveactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(executiveactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201604231413225_executiveactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
