// <auto-generated />
namespace TeamJAMiN.DataContexts.GalleristComponentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlayerGalleries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayerGalleries));
        
        string IMigrationMetadata.Id
        {
            get { return "201603251514175_PlayerGalleries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
